version: "3.9"
services:
  ovpn:
    image: kylemanna/openvpn
    restart: always
    volumes:
      - ovpn-data:/etc/openvpn:rw
    ports:
      # - [local_port]:1194/udp
    cap_add:
      - NET_ADMIN
      
volumes:
  ovpn-data:
    external: true